spring:
  application:
    name: GATEWAY-SERVICE-SECURITY
zuul:
   routes:
     user-service:
       path: /user-service/**
       uri: lb://user-service

     plan-service:
        path: /plan/**
        uri: lb://plan-service

     promocode-service:
       #path: /promo/**
       uri: lb://promocode-service
          
        
                
server:
  port: 8909
  
 